input {
  beats {
    port => 5044
  }
  tcp {
    port => 50000
    codec => json_lines
  }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-j-8.0.33.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://mysql:3306/sparta?useSSL=false&allowPublicKeyRetrieval=true"
    jdbc_user => "root"
    jdbc_password => "root"
    schedule => "*/1 * * * *"
    jdbc_fetch_size => 500
    jdbc_page_size => 500
    statement => "
      SELECT
          p.product_public_id,
          p.color,
          p.image,
          p.category,
          p.description,
          p.name,
          pv.price,
          b.brand_name,
          p.product_id,
          p.brand_id,
          p.created_at,
          p.is_deleted,
          GREATEST(COALESCE(p.updated_at, p.created_at), pv.created_at) as record_updated_at
      FROM sparta.ED_PRODUCT p
      JOIN sparta.ED_BRANDS b
        ON p.brand_id = b.brand_id
      JOIN (
          SELECT pv1.*
          FROM sparta.ED_PRODUCT_PRICE_VERSION pv1
          INNER JOIN (
              SELECT product_id, MAX(created_at) as max_created_at
              FROM sparta.ED_PRODUCT_PRICE_VERSION
              WHERE is_current_version = true
              GROUP BY product_id
          ) pv2 ON pv1.product_id = pv2.product_id
          AND pv1.created_at = pv2.max_created_at
      ) pv ON p.product_id = pv.product_id
      WHERE GREATEST(COALESCE(p.updated_at, p.created_at), pv.created_at) > :sql_last_value
      AND p.is_deleted = false
      ORDER BY record_updated_at ASC
      LIMIT 20000
    "
    tracking_column => "record_updated_at"
    tracking_column_type => "timestamp"
    use_column_value => true
    last_run_metadata_path => "/usr/share/logstash/last_run_metadata"
    type => "product"
  }
}

output {
  if [type] == "product" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "products"
      document_id => "%{product_id}"
      user => "elastic"
      password => "password"
    }
  } else {
    elasticsearch {
      hosts => "elasticsearch:9200"
      index => "springboot-elk"
      user => "elastic"
      password => "password"
    }
  }
}